package com.jeffy.jforle.common.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WossUsers generated by MyEclipse Persistence Tools
 */

public class Users implements java.io.Serializable {

	// Fields

	private Long id;
	private String loginName;
	private String loginPassword;
	private String realName;
	private String telephone;
	private Date registerdate;
	private String sex;
	private String postcode;
	private String address;
	private String email;
	private String remark;

	// Constructors

	/** default constructor */
	public Users() {
	}

	/** minimal constructor */
	public Users(String loginName, String loginPassword, String address,
			String email) {
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.address = address;
		this.email = email;
	}

	/** full constructor */
	public Users(String loginName, String loginPassword, String realName,
			String telephone, Date registerdate, String sex, String postcode,
			String address, String email, String remark) {
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.realName = realName;
		this.telephone = telephone;
		this.registerdate = registerdate;
		this.sex = sex;
		this.postcode = postcode;
		this.address = address;
		this.email = email;
		this.remark = remark;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(Date registerdate) {
		this.registerdate = registerdate;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}